export const ProductsDb = [
  {
    id: 1,
    name: "Handmade Kente Bag",
    price: 10.00,
    category: "Handbag",
    brand: "Ankara",
    imageUrl: "/Kente bag.png", 
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Celebrate heritage and style with this vibrant African handbag, showcasing traditional geometric patterns."
  },
  {
    id: 2,
    name: "Soft Blue Tote Bag",
    price: 2.99,
    category: "Handbag",
    brand: "Tote",
    imageUrl: "/faux blue coach.png",
    rating: 4,
    inStock: false,
    inStore: false,
    description: "Step out in style with this elegant structured tote, featuring a refined inspired patter in a soft blue colorway."
  },
  {
    id: 3,
    name: "Classic Bucket Shoulder Bag",
    price: 15.99,
    category: "Handbag",
    brand: "Shoulder Bag",
    imageUrl: "/bucket style handbag.png",
    rating: 5,
    inStock: true,
    inStore: true,
    description: "Elevate your everyday look with this stylish bucket shoulder bag, designed in a timeless tan and brown color palette."
  },
  {
    id: 4,
    name: "Black Animal Print",
    price: 8.99,
    category: "Handbag",
    brand: "Crossbody",
    imageUrl: "/animal print.png",
    rating: 2,
    inStock: true,
    inStore: false,
    description: "Make a bold statement with this compact shoulder bag featuring a sleek black base and eye-catching animal print detail."
  },
  {
    id: 5,
    name: "Black Mini Satchel",
    price: 14.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/Black bag.png",
    rating: 3,
    inStock: false,
    inStore: true,
    description: "This mini satchel is a perfect blend of structure and style, designed with a top handle, t’s ideal for carrying just the essentials while adding a polished finish to your look."
  },
  {
    id: 6,
    name: "Pink Reptile Bag & Wallet",
    price: 6.99,
    category: "Handbag",
    brand: "Crossbody",
    imageUrl: "/snake skin bag.png",
    rating: 4,
    inStock: true,
    inStore: false,
    description: "Sleek and edgy, this mini shoulder bag features a striking faux reptile texture in a bold black finish. Compact yet stylish, perfect for adding a touch of style to your night look."
  },
  {
    id: 7,
    name: "Black Satchel",
    price: 19.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/black-bag 2.png",
    rating: 5,
    inStock: true,
    inStore: true,
    description: "Faux letter bag perfect for the night out, black handbag with a glossy finish."
  },
  {
    id: 8,
    name: "Pebble Top Satchel",
    price: 9.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/faux brown bag.png",
    rating: 2,
    inStock: true,
    inStore: true,
    description: "Brown, structured handbag with a smooth textured finish. Pair with a patterned scraf to add a touch of elegance."
  },
  {
    id: 9,
    name: "Black Print & Wallet",
    price: 11.99,
    category: "Handbag",
    brand: "Tote",
    imageUrl: "/black-MK.png",
    rating: 4,
    inStock: false,
    inStore: false,
    description: "A stylish and practicle choice for the fashion conscious individual. This tote keep things polished with its structured shape and sturdy handles."
  },
  {
    id: 10,
    name: "Blue Reptile Bag & Wallet",
    price: 24.99,
    category: "Handbag",
    brand: "Crossbody",
    imageUrl: "/blue croc satchel.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Chic and compact, this mini shoulder bag stands out with its faux reptile texture in a cool blue finish, Just the right size to bring a pop of style to your night-out look."
  },
  {
    id: 11,
    name: "Burgundy Satchel",
    price: 14.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/burgundy bag.png",
    rating: 3,
    inStock: false,
    inStore: true,
    description: "Designed for both style and function, it features a rich, deep hue that adds a touch of elegance to any outfit."
  },
  {
    id: 12,
    name: "Sunflower",
    price: 6.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/sunflower bag.png",
    rating: 4,
    inStock: true,
    inStore: false,
    description: "Bright and playful,the sunflower a unqiue semi circular multi-colored handbag with a metal buckle. Finished with a black handle, perfect for days when you want your bag to do the talking."
  },
  {
    id: 13,
    name: "Handmade Kente ",
    price: 19.99,
    category: "Handbag",
    brand: "Ankara",
    imageUrl: "/red-kente-african-bag.png",
    rating: 5,
    inStock: true,
    inStore: true,
    description: "Lightweight fabric with woven handles, vibrant red base color adorned with african patterns this tote is perfect for an every day look."
  },
  {
    id: 14,
    name: "Stitched Color Block Patchwork",
    price: 9.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/stitched-color-block-satchel.png",
    rating: 2,
    inStock: true,
    inStore: true,
    description: "This color block patchwork satchel brings a playful twist to your everyday style. Made with smooth faux leather and shiny gold-tone hardware, its roomy enough for your daily must-haves and polished enough for work or weekend plans."
  },
  {
    id: 15,
    name: "Black Tote Bag",
    price: 11.99,
    category: "Handbag",
    brand: "Tote",
    imageUrl: "/black tote bag.png",
    rating: 4,
    inStock: false,
    inStore: false,
    description: "Easygoing with a touch of edge, this bucket bag brings everyday style to a whole new level. With its flat base and wide open top, it’s perfect for tossing in your essentials and heading out."
  },
  {
    id: 16,
    name: "Green Ankara Bag",
    price: 24.99,
    category: "Handbag",
    brand: "Ankara",
    imageUrl: "/green-african bag.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Made from African wax fabric, this ankara bag is lined with cloth, designed to be used for causual and formal occasions."
  },
  {
    id: 17,
    name: "Faux Reptile Bag & Wallet",
    price: 24.99,
    category: "Handbag",
    brand: "Crossbody",
    imageUrl: "/pink bag.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Blush pink mini shoulder bag features a faux reptile texture,  Compact and stylish, its the perfect pop of charm for brunch dates, night strolls, or anytime you want to keep things light and lovely."
  },
  {
    id: 18,
    name: "Faux Reptile Bag & Wallet",
    price: 24.99,
    category: "Handbag",
    brand: "Crossbody",
    imageUrl: "/pink and blue.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "A bold faux reptile texture with a dreamy mixture of blue and pink perfect blend of cool and cute, just the right size to carry your essentials with a pop of personality."
  },
   {
    id: 19,
    name: "Multi-Colored Ankara",
    price: 24.99,
    category: "Handbag",
    brand: "Ankara",
    imageUrl: "/multi-colored ankara bag.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Casual yet stylish with colorful design patterns suitable for every day use or as a statement piece, The bright bold patterns make it eye catching and distinctive."
  },
  {
    id: 20,
    name: "LV Tote Bag",
    price: 24.99,
    category: "Handbag",
    brand: "Tote",
    imageUrl: "/LV brown and black bag.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Chic and timeless, this faux leather tote captures the iconic LV-inspired look,  designed with double top handles and roomy enough for your daily essentials, it blends elegance and practicality in one effortless carry-all."
  },

  //List of clothing 
  {
    id: 21,
    name: "Women's Black Legging",
    price: 24.99,
    category: "Clothing",
    brand: "",
    imageUrl: "/black-leggings.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Stylish black leggings comfortable for work or at home stay."
  },
  {
    id: 22,
    name: "Traditional African Dress",
    price: 24.99,
    category: "Clothing",
    brand: "Kaftan",
    imageUrl: "/green-african dress.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Green inspired Ankara dress brings elegance and energy to every step. Made to stand out, speak out loud and honor roots with style."
  },
  {
    id: 23,
    name: "Multi-Colored African Dresses",
    price: 24.99,
    category: "Clothing",
    brand: "Kaftan",
    imageUrl: "/african dresses.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Celebrate culture and confidence in these stunning African-inspired dresses, crafted with vibrant prints and rich colors that tell a story. Designed with flowing fabric and bold patterns."
  },
  {
    id: 24,
    name: "Purple Print Kaftan",
    price: 24.99,
    category: "Clothing",
    brand: "Kaftan",
    imageUrl: "/purple kaftan.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Drape yourself in elegance with this stunning purple kaftan dress, where comfort meets timeless beauty."
  },
  {
    id: 25,
    name: "Red Print Kaftan",
    price: 24.99,
    category: "Clothing",
    brand: "Kaftan",
    imageUrl: "/red-kaftan.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Red silhouette kaftan dress perfect for both lounging in style and stepping out with grace."
  },
  {
    id: 26,
    name: "Nigerian Kaftan",
    price: 24.99,
    category: "Clothing",
    brand: "Kaftan",
    imageUrl: "/nigerian kaftan.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Turn heads and lift spirits in this vibrant blue and yellow kaftan, a joyful blend of colorful colors and sunshine energy."
  },
  {
    id: 27,
    name: "Ankara Skirt",
    price: 24.99,
    category: "Clothing",
    brand: "Kaftan",
    imageUrl: "/multicolored skirts.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Celebrate your roots with this stunning African skirt, bursting with color and confidence, this skirt brings movement, tradition, and modern flair to your wardrobe."
  },
  {
    id: 28,
    name: "Traditional African Dress",
    price: 24.99,
    category: "Clothing",
    brand: "",
    imageUrl: "/green-african dress.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Traditional African wear with green patterns and matching headwrap ."
  },
  {
    id: 29,
    name: "Traditional African Dress",
    price: 24.99,
    category: "Clothing",
    brand: "",
    imageUrl: "/green-african dress.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Traditional African wear with green patterns and matching headwrap ."
  },


];
