export const ProductsDb = [
  // this is for bags
  {
    id: 1,
    name: "Handmade Kente Bag",
    price: 10.00,
    category: "Handbag",
    brand: "Ankara",
    imageUrl: "/Kente bag.png", 
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Celebrate heritage and style with this vibrant African handbag, showcasing traditional geometric patterns."
  },
  {
    id: 2,
    name: "Soft Blue Tote Bag",
    price: 2.99,
    category: "Handbag",
    brand: "Tote",
    imageUrl: "/faux blue coach.png",
    rating: 4,
    inStock: false,
    inStore: false,
    description: "Step out in style with this elegant structured tote, featuring a refined inspired patter in a soft blue colorway."
  },
  {
    id: 3,
    name: "Classic Bucket Shoulder Bag",
    price: 15.99,
    category: "Handbag",
    brand: "Shoulder Bag",
    imageUrl: "/bucket style handbag.png",
    rating: 5,
    inStock: true,
    inStore: true,
    description: "Elevate your everyday look with this stylish bucket shoulder bag, designed in a timeless tan and brown color palette."
  },
  {
    id: 4,
    name: "Black Animal Print",
    price: 8.99,
    category: "Handbag",
    brand: "Crossbody",
    imageUrl: "/animal print.png",
    rating: 2,
    inStock: true,
    inStore: false,
    description: "Make a bold statement with this compact shoulder bag featuring a sleek black base and eye-catching animal print detail."
  },
  {
    id: 5,
    name: "Black Mini Satchel",
    price: 14.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/Black bag.png",
    rating: 3,
    inStock: false,
    inStore: true,
    description: "This mini satchel is a perfect blend of structure and style, designed with a top handle, t’s ideal for carrying just the essentials while adding a polished finish to your look."
  },
  {
    id: 6,
    name: "Pink Reptile Bag & Wallet",
    price: 6.99,
    category: "Handbag",
    brand: "Crossbody",
    imageUrl: "/snake skin bag.png",
    rating: 4,
    inStock: true,
    inStore: false,
    description: "Sleek and edgy, this mini shoulder bag features a striking faux reptile texture in a bold black finish. Compact yet stylish, perfect for adding a touch of style to your night look."
  },
  {
    id: 7,
    name: "Black Satchel",
    price: 19.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/black-bag 2.png",
    rating: 5,
    inStock: true,
    inStore: true,
    description: "Faux letter bag perfect for the night out, black handbag with a glossy finish."
  },
  {
    id: 8,
    name: "Pebble Top Satchel",
    price: 9.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/faux brown bag.png",
    rating: 2,
    inStock: true,
    inStore: true,
    description: "Brown, structured handbag with a smooth textured finish. Pair with a patterned scraf to add a touch of elegance."
  },
  {
    id: 9,
    name: "Black Print & Wallet",
    price: 11.99,
    category: "Handbag",
    brand: "Tote",
    imageUrl: "/black-MK.png",
    rating: 4,
    inStock: false,
    inStore: false,
    description: "A stylish and practicle choice for the fashion conscious individual. This tote keep things polished with its structured shape and sturdy handles."
  },
  {
    id: 10,
    name: "Blue Reptile Bag & Wallet",
    price: 24.99,
    category: "Handbag",
    brand: "Crossbody",
    imageUrl: "/blue croc satchel.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Chic and compact, this mini shoulder bag stands out with its faux reptile texture in a cool blue finish, Just the right size to bring a pop of style to your night-out look."
  },
  {
    id: 11,
    name: "Burgundy Satchel",
    price: 14.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/burgundy bag.png",
    rating: 3,
    inStock: false,
    inStore: true,
    description: "Designed for both style and function, it features a rich, deep hue that adds a touch of elegance to any outfit."
  },
  {
    id: 12,
    name: "Sunflower",
    price: 6.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/sunflower bag.png",
    rating: 4,
    inStock: true,
    inStore: false,
    description: "Bright and playful,the sunflower a unqiue semi circular multi-colored handbag with a metal buckle. Finished with a black handle, perfect for days when you want your bag to do the talking."
  },
  {
    id: 13,
    name: "Handmade Kente ",
    price: 19.99,
    category: "Handbag",
    brand: "Ankara",
    imageUrl: "/red-kente-african-bag.png",
    rating: 5,
    inStock: true,
    inStore: true,
    description: "Lightweight fabric with woven handles, vibrant red base color adorned with african patterns this tote is perfect for an every day look."
  },
  {
    id: 14,
    name: "Stitched Color Block Patchwork",
    price: 9.99,
    category: "Handbag",
    brand: "Satchel",
    imageUrl: "/stitched-color-block-satchel.png",
    rating: 2,
    inStock: true,
    inStore: true,
    description: "This color block patchwork satchel brings a playful twist to your everyday style. Made with smooth faux leather and shiny gold-tone hardware, its roomy enough for your daily must-haves and polished enough for work or weekend plans."
  },
  {
    id: 15,
    name: "Black Tote Bag",
    price: 11.99,
    category: "Handbag",
    brand: "Tote",
    imageUrl: "/black tote bag.png",
    rating: 4,
    inStock: false,
    inStore: false,
    description: "Easygoing with a touch of edge, this bucket bag brings everyday style to a whole new level. With its flat base and wide open top, it’s perfect for tossing in your essentials and heading out."
  },
  {
    id: 16,
    name: "Green Ankara Bag",
    price: 24.99,
    category: "Handbag",
    brand: "Ankara",
    imageUrl: "/green-african bag.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Made from African wax fabric, this ankara bag is lined with cloth, designed to be used for causual and formal occasions."
  },
  {
    id: 17,
    name: "Faux Reptile Bag & Wallet",
    price: 24.99,
    category: "Handbag",
    brand: "Crossbody",
    imageUrl: "/pink bag.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Blush pink mini shoulder bag features a faux reptile texture,  Compact and stylish, its the perfect pop of charm for brunch dates, night strolls, or anytime you want to keep things light and lovely."
  },
  {
    id: 18,
    name: "Faux Reptile Bag & Wallet",
    price: 24.99,
    category: "Handbag",
    brand: "Crossbody",
    imageUrl: "/pink and blue.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "A bold faux reptile texture with a dreamy mixture of blue and pink perfect blend of cool and cute, just the right size to carry your essentials with a pop of personality."
  },
   {
    id: 19,
    name: "Multi-Colored Ankara",
    price: 24.99,
    category: "Handbag",
    brand: "Ankara",
    imageUrl: "/multi-colored ankara bag.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Casual yet stylish with colorful design patterns suitable for every day use or as a statement piece, The bright bold patterns make it eye catching and distinctive."
  },
  {
    id: 20,
    name: "LV Tote Bag",
    price: 24.99,
    category: "Handbag",
    brand: "Tote",
    imageUrl: "/LV brown and black bag.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Chic and timeless, this faux leather tote captures the iconic LV-inspired look,  designed with double top handles and roomy enough for your daily essentials, it blends elegance and practicality in one effortless carry-all."
  },

  //List of clothing 
  {
    id: 21,
    name: "Women's Black Legging",
    price: 24.99,
    category: "Women Dresses",
    brand: "African",
    imageUrl: "/black-leggings.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Stylish black leggings comfortable for work or at home stay."
  },
  {
    id: 22,
    name: "Traditional African Dress",
    price: 24.99,
    category: "Women Dresses",
    brand: "African",
    imageUrl: "/green-african-dress.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Green inspired Ankara dress brings elegance and energy to every step. Made to stand out, speak out loud and honor roots with style."
  },
  {
    id: 23,
    name: "Multi-Colored African Dresses",
    price: 24.99,
    category: "Women Dresses",
    brand: "African",
    imageUrl: "/african dresses.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Celebrate culture and confidence in these stunning African-inspired dresses, crafted with vibrant prints and rich colors that tell a story. Designed with flowing fabric and bold patterns."
  },
  {
    id: 24,
    name: "Purple Print Kaftan",
    price: 24.99,
    category: "Women Dresses",
    brand: "African",
    imageUrl: "/purple-kaftan.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Drape yourself in elegance with this stunning purple kaftan dress, where comfort meets timeless beauty."
  },
  {
    id: 25,
    name: "Red Print Kaftan",
    price: 24.99,
    category: "Women Dresses",
    brand: "African",
    imageUrl: "/red-kaftan-dress.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Red silhouette kaftan dress perfect for both lounging in style and stepping out with grace."
  },
  {
    id: 26,
    name: "Nigerian Kaftan",
    price: 24.99,
    category: "Women Dresses",
    brand: "African",
    imageUrl: "/nigerian-kaftan.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Turn heads and lift spirits in this vibrant blue and yellow kaftan, a joyful blend of colorful colors and sunshine energy."
  },
  {
    id: 27,
    name: "Ankara Skirt",
    price: 24.99,
    category: "Women Dresses",
    brand: "African",
    imageUrl: "/multicolored skirts.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Celebrate your roots with this stunning African skirt, bursting with color and confidence, this skirt brings movement, tradition, and modern flair to your wardrobe."
  },
  {
    id: 28,
    name: "Traditional African Dress",
    price: 24.99,
    category: "Women Dresses",
    brand: "African",
    imageUrl: "/fall-colored-dress.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Traditional African wear with green and orange patterns and matching headwrap ."
  },
  {
    id: 29,
    name: "Women's Dress",
    price: 24.99,
    category: "Women Dresses",
    brand: "African",
    imageUrl: "/light-blue-dress.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Traditional African wear with green and orange patterns and matching headwrap ."
  },

  {
    id: 30,
    name: "Button Down Collar Summer Shirt",
    price: 24.99,
    category: "Men Shirts",
    brand: "African",
    imageUrl: "/blue stripped shirt.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Casual short sleeve top for men. Basic stripped shirt, classic fit. Excellent comfort to be worn in any occasion."
  },
   {
    id: 31,
    name: "Men Geometric Print Dashiki Shirt",
    price: 24.99,
    category: "Men Shirts",
    brand: "African",
    imageUrl: "/zigzag-shirt.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Make a bold statement with this vibrant short-sleeve dashiki-style shirt, where tradition meets contemporary design.Featuring a striking geometric pattern in red, black, beige, and blue, this shirt celebrates African-inspired motifs with a modern edge."
  },
  {
    id: 32,
    name: "Earth-Tone Heritage Print",
    price: 24.99,
    category: "Men Shirts",
    brand: "African",
    imageUrl: "/tribal-shirt.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Step into effortless style with this short-sleeve button-up shirt featuring a bold mud cloth-inspired print. Rooted in West African tradition, the design uses earthy tones of burnt orange, black, and beige to create a patchwork of tribal patterns."
  },
  {
    id: 33,
    name: "Men's Ankara Dashiki Shirt",
    price: 24.99,
    category: "Men Shirts",
    brand: "African",
    imageUrl: "/blue-pink-shirt.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Lightweight and breathable, this short-sleeve shirt is made for celebrations, summer days, and moments that call for color and confidence. This vibrant yellow base is adorned with vibrant paisley and floral motifs in magenta, turquoise, and deep green evoking a rich cultural storytelling through fabric. "
  },
   {
    id: 34,
    name: "Men's Striped Printed Shirt ",
    price: 24.99,
    category: "Men Shirts",
    brand: "African",
    imageUrl: "/blue-orange-stripped-shirt.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Elevate your everyday style with this versatile striped printed shirt. Designed for the modern man, this piece features a sleek vertical stripe pattern that elongates the silhouette and adds a touch of sophistication to any outfit."
  },
     {
    id: 35,
    name: "Traditional African Shirt",
    price: 24.99,
    category: "Men Shirts",
    brand: "African",
    imageUrl: "/traditional-african-shirt.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Celebrate culture and craftsmanship with this traditional African shirt, a vibrant reflection of ancestral artistry and modern pride.The bold patterns and rich color palettes tell stories that transcend borders, while the breathable fabric and relaxed fit ensure comfort in every setting, from community gatherings to everyday wear."
  },
     {
    id: 36,
    name: "Timeless Heritage African Shirt",
    price: 24.99,
    category: "Men Shirts",
    brand: "African",
    imageUrl: "/african-ptinted-circles.jpg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Make a fearless statement with this African print shirt, where vivid color meets symbolic design. Featuring a striking array of circular patterns—each one echoing themes of unity, life, and connection—this shirt is a wearable work of art."
  },


  //Body Butters
  {
    id: 37,
    name: "Cocoa Butter Whipped Shea Butter",
    price: 24.99,
    category: "Body Care",
    brand: "Mine Botanicals",
    imageUrl: "/cocoa butter.webp",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Derived from cocoa beans, it has a chocolatey scent and is known for its moisturizing and occlusive properties, meaning it creates a protective barrier on the skin. The combination of cocoa and shea butters provides deep hydration for dry and damaged skin. "
  },
  {
    id: 38,
    name: "Mango Whipped Shea Butter",
    price: 24.99,
    category: "Body Care",
    brand: "Mine Botanicals",
    imageUrl: "/Mango Butter.jpeg",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Mango butter is rich in vitamins A, C, and E, while shea butter is packed with vitamins A, E, and F, and fatty acids. These nutrients help to nourish and protect the skin."
  },
  {
    id: 39,
    name: "Organic African Shea Butter",
    price: 24.99,
    category: "Body Care",
    brand: "RA cosmetics",
    imageUrl: "/shea butter.webp",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Natural Unrefined African Shea Butter, nourishes hydrates hair & skin, promoting softness, elasticity, and a healthy, radiant glow. Rich in vitamins (A, E, F, K), antioxidants, essential fatty acids including stearic and oleic acids. "
  },
  {
    id: 40,
    name: "Strawberry Whipped Shea Butter",
    price: 24.99,
    category: "Body Care",
    brand: "Mine Botanicals",
    imageUrl: "/strawberry whipped butter.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Strawberry Whipped Shea Butter with Honey & Vitamin-E Cleansing, Soothing & Anti-Inflammatory."
  },
   {
    id: 41,
    name: "Dudu-Osun Black Soap",
    price: 24.99,
    category: "Body Care",
    brand: "Dudu-Osun",
    imageUrl: "/dudu soap.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "African black soap originally from West Africa. Black soap gets its natural color from the ashes of plantain peels, cocoa pods, and palm bunches. Used for deep cleansing, natural exfoliation, and moisturizing. "
  },
   {
    id: 42,
    name: "African Black Soap",
    price: 24.99,
    category: "Body Care",
    brand: "By Natures Organics",
    imageUrl: "/african_black_soap.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "African black soap is a traditional skin and hair cleanser used for its cleansing and natural clarifying properties. It is both simple and highly effective for keeping skin looking its best."
  },
   {
    id: 43,
    name: "DHMS International Shea Butter",
    price: 24.99,
    category: "Body Care",
    brand: "DHMS International",
    imageUrl: "/DHMS clear shea butter.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "100% Natural Moisture for Skin & Hair. Indulge your skin and hair with our handcrafted Whipped Shea Butter, made from pure, unrefined shea butter sourced from West Africa and blended with nourishing botanical oils."
  },
   {
    id: 44,
    name: "DHMS International Shea Butter",
    price: 24.99,
    category: "Body Care",
    brand: "",
    imageUrl: "/DHMS shea butter.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "This rich, golden butter is ethically sourced and handcrafted in West Africa. Infused with borututu root, Shea Butter deeply nourishes dry skin, soothes irritation, and supports skin renewal. Perfect for daily use on skin, hair, and scalp."
  },
  //Fragrance Oil
   {
    id: 45,
    name: "Golden Sand Oil - Warm, Earthy and Seductive",
    price: 24.99,
    category: "Body Care",
    brand: "Fragrance Oil",
    imageUrl: "/golden sand oil.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Captivating oil that evokes warmth, sensuality, and mystery. With its deep amber hue and luxurious texture, this oil wraps the skin in a soft, lingering scent that blends sun-warmed earth, soft florals, and a touch of sweet musk."
  },
   {
    id: 46,
    name: "FlowerBomb",
    price: 24.99,
    category: "Body Care",
    brand: "Fragrance Oil",
    imageUrl: "/flower bomb oil.png",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Immerse yourself in the delicate beauty of a floral fragrance. This scent captures the essence of blooming petals, fresh, elegant, and endlessly feminine."
  },
   {
    id: 47,
    name: "Dior Homme Oil",
    price: 24.99,
    category: "Body Care",
    brand: "Fragrance Oil",
    imageUrl: "/dior homme oil.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Dior Homme Oil reimagines masculine elegance with a fluid, sensual twist. This luxurious perfumed body oil carries the signature Dior Homme scent—a refined balance of fresh bergamot, powdery iris, and warm woody notes like vetiver and cedar."
  },
  {
    id: 48,
    name: "Patchouli Oil",
    price: 24.99,
    category: "Body Care",
    brand: "Fragrance Oil",
    imageUrl: "/Patchouli oil.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Patchouli Oil is a deep, musky essential oil cherished for its rich, earthy aroma and calming properties. Distilled from the leaves of the patchouli plant, its scent is warm, woody, and slightly sweet—with a hint of spice and resin that lingers beautifully on the skin."
  },
  {
    id: 49,
    name: "Paco Rabanne Oil",
    price: 24.99,
    category: "Body Products",
    brand: "Fragrance Oil",
    imageUrl: "/paco rabanne oil.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Paco Rabanne Oil captures the daring spirit of the original fragrance in a concentrated long-lasting oil form. Rich, seductive, and endlessly modern, this perfumed body oil wraps the skin in an unforgettable blend of warm spices, fresh citrus, and deep, woody undertones."
  },
    {
    id: 44,
    name: "Peppermint Oil - Awaken the mind. Electrify the senses.",
    price: 24.99,
    category: "Body Products",
    brand: "Fragrance Oil",
    imageUrl: "/peppermint oil.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Steam-distilled from wild mint leaves, this oil carries a pure, sharp freshness with hints of icy green, crushed herb, and the slightest touch of earth beneath. Use it to clear mental fog, to refocus breath, or to soothe tension from the temples to the toes. Whether in a diffuser, a massage blend, or dabbed behind the ears, peppermint becomes your private ritual for reset and renewal."
  },
     {
    id: 44,
    name: "Seductress Body Oil - Unveil the essence of temptation",
    price: 24.99,
    category: "Body Products",
    brand: "Fragrance Oil",
    imageUrl: "/lick me all over oil.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "This luxurious elixir is more than just a body oil. Seductress envelops your body in a radiant sheen that beckons attention. Grab one today, wear it as your invisible armor of sensuality."
  },
     {
    id: 45,
    name: "Michelle Obama Inspired Oil - Inspired by the quiet power of presence.",
    price: 24.99,
    category: "Body Products",
    brand: "Fragrance Oil",
    imageUrl: "/Michelle Obama oil.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "This is not just a floral scent, it’s a statement. A graceful equilibrium of floral sophistication and grounded wisdom. Wear it when you want to be remembered; not just seen."
  },
    {
    id: 46,
    name: "Mousuf Wardi Roll-On Perfume Oil",
    price: 24.99,
    category: "Body Products",
    brand: "Mousuf Wardi",
    imageUrl: "/mousuf wardi.jpg",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "This perfume oil is a floral fruity gourmand. Top notes include red lychee, rhubarb, and strawberry. Middle notes of rose, vanilla and apple. Base notes white musk and cashmeran. Turn heads this summer by smelling good & feeling good."
  },
    {
    id: 47,
    name: "Guilty Intention – Inspired by Gucci Guilty Pour Homme",
    price: 24.99,
    category: "Body Products",
    brand: "Fragrance Oil",
    imageUrl: "/gucci guilty.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Darkly smooth and provocatively refined, this body oil captures the magnetic allure of confidence in motion. As it warms on the skin, the heart notes unfold: orange blossom and neroli, unexpected and sensual, softening the sharp lines with an undercurrent of intrigue. Suitable for the man who's unapologetically himself. Seductive. Sophisticated. Unforgettable."
  },
  //Fragrances
   {
    id: 48,
    name: "Lattafa Asad Eau de Parfum ",
    price: 24.99,
    category: "Body Products",
    brand: "Fragrance",
    imageUrl: "/Lattafa black.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Eau De Parfum, Lattafa Asad is a vanilla fragrance with a spicy, woody, and ambery fragrance with a touch of sweetness. Perfect for summer adventures and exotic destinations. "
  },
   {
    id: 49,
    name: "Lattafa Asad Bourbon Eau de Parfum ",
    price: 24.99,
    category: "Body Products",
    brand: "Fragrance",
    imageUrl: "/Lattafa brown.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Asad Bourbon bridges spice, warmth, and sweetness in a bold, modern way. Crafted for men who command attention with quiet confidence. This fragrance opens with a base of bourbon vanilla and amber inviting a sensual warmth, smooth, smoky and undeniably magnetic. Perfect for cooler seasons and evening wear."
  },
    {
    id: 50, 
    name: "Lattafa Asad Yara Eau de Parfum",
    price: 24.99,
    category: "Body Products",
    brand: "Fragrance",
    imageUrl: "/Lattafa orange.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Discover the charm of Lattafa Yara, a dreamy modern fragrance that wraps you in delicate sweetness and soft sophistication. Base notes of tangerine, heliotrope and orchid, it invites you in with warmth and grace. "
  },
   {
    id: 51, 
    name: "Lattafa Yara Moi Eau de Parfum",
    price: 24.99,
    category: "Body Products",
    brand: "Fragrance",
    imageUrl: "/lattafa white.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Wrap yourself in the delicate warmth of Yara Moi a soft, sweet floral fragrance with a modern gourmand twist. This elegant scent opens with notes of juicy peach and fresh jasmine, offering a luminous and inviting first impression."
  },
  //Hair care
   {
    id: 52, 
    name: "Luxury Silk Bonnet",
    price: 24.99,
    category: "Hair",
    brand: "Bonnet",
    imageUrl: "/yellow-bonnet.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Wrap your hair in luxury while you sleep. Our 100% silk bonnet is designed to preserve moisture, reduce frizz, and protect delicate strands whether you're maintaining curls, coils, or a blowout."
  },
  {
    id: 53, 
    name: "Luxe Statement Silk Bonnett",
    price: 24.99,
    category: "Hair",
    brand: "Bonnet",
    imageUrl: "/orange-bonnet.png",
    rating: 4,
    inStock: true,
    inStore: true,
    description: "Designed to protect your hair while making a statement, this bonnet is crafted from high-quality silk for a smooth, friction-free finish that reduces breakage, preserves moisture, and maintains your style overnight."
  },



];

