export const ProductsDb = [
  {
    id: 1,
    name: "Shea Butter Hair Cream",
    price: 10.99,
    category: "Hair",
    brand: "Shea Butter",
    imageUrl: "/butter1.webp",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "Nourish and hydrate dry hair with this rich shea butter cream, perfect for daily moisturizing."
  },
  {
    id: 2,
    name: "Shea Moisture Body Lotion",
    price: 12.99,
    category: "Skincare",
    brand: "Shea Moisture",
    imageUrl: "/moisture.png",
    rating: 4,
    inStock: false,
    inStore: false,
    description: "Deeply moisturizing body lotion infused with shea butter to soften and smooth skin."
  },
  {
    id: 3,
    name: "Mielle Curl Defining Gel",
    price: 15.99,
    category: "Hair",
    brand: "Mielle",
    imageUrl: "/mielle.webp",
    rating: 5,
    inStock: true,
    inStore: true,
    description: "Defines curls with a soft hold and enhances shine without stiffness or flaking."
  },
  {
    id: 4,
    name: "Olive Oil Nail Strengthener",
    price: 8.99,
    category: "Nail Art",
    brand: "Olive Oil",
    imageUrl: "/olive.webp",
    rating: 2,
    inStock: true,
    inStore: false,
    description: "Strengthens and conditions nails with the power of olive oil for healthier growth."
  },
  {
    id: 5,
    name: "Organics Facial Cleanser",
    price: 14.99,
    category: "Skincare",
    brand: "Organics",
    imageUrl: "/clean.jpg",
    rating: 3,
    inStock: false,
    inStore: true,
    description: "Gentle foaming cleanser that removes impurities while keeping skin soft and balanced."
  },
  {
    id: 6,
    name: "Dextol Antibacterial Wipes",
    price: 6.99,
    category: "Body Care",
    brand: "Dextol",
    imageUrl: "/wipes.jpg",
    rating: 4,
    inStock: true,
    inStore: false,
    description: "Convenient antibacterial wipes for quick and effective germ protection on the go."
  },
  {
    id: 7,
    name: "Xpression Braiding Hair",
    price: 19.99,
    category: "Hair",
    brand: "Xpression",
    imageUrl: "/braids.jpg",
    rating: 5,
    inStock: true,
    inStore: true,
    description: "Premium synthetic braiding hair ideal for protective styles with a natural look."
  },
  {
    id: 8,
    name: "Nail Art Brush Set",
    price: 9.99,
    category: "Nail Art",
    brand: "Nail Art",
    imageUrl: "/brushnet.webp",
    rating: 2,
    inStock: true,
    inStore: true,
    description: "Complete brush set for intricate nail art designs and professional-quality finishes."
  },
  {
    id: 9,
    name: "Fragrance Mist - Vanilla",
    price: 11.99,
    category: "Fragrance",
    brand: "Mielle",
    imageUrl: "/fragarance.webp",
    rating: 4,
    inStock: false,
    inStore: false,
    description: "Sweet vanilla body mist that leaves you feeling fresh and delicately scented."
  },
  {
    id: 10,
    name: "Jewlery & Accessories Pack",
    price: 24.99,
    category: "Jewelery & Accessories",
    brand: "Shea Moisture",
    imageUrl: "/accessories.webp",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "A curated pack of stylish jewelry and accessories to complement any outfit."
  },
  {
    id: 11,
    name: "Organics Facial Cleanser",
    price: 14.99,
    category: "Skincare",
    brand: "Organics",
    imageUrl: "/clean.jpg",
    rating: 3,
    inStock: false,
    inStore: true,
    description: "Gentle foaming cleanser that removes impurities while keeping skin soft and balanced."
  },
  {
    id: 12,
    name: "Dextol Antibacterial Wipes",
    price: 6.99,
    category: "Body Care",
    brand: "Dextol",
    imageUrl: "/wipes.jpg",
    rating: 4,
    inStock: true,
    inStore: false,
    description: "Convenient antibacterial wipes for quick and effective germ protection on the go."
  },
  {
    id: 13,
    name: "Xpression Braiding Hair",
    price: 19.99,
    category: "Hair",
    brand: "Xpression",
    imageUrl: "/braids.jpg",
    rating: 5,
    inStock: true,
    inStore: true,
    description: "Premium synthetic braiding hair ideal for protective styles with a natural look."
  },
  {
    id: 14,
    name: "Nail Art Brush Set",
    price: 9.99,
    category: "Nail Art",
    brand: "Nail Art",
    imageUrl: "/brushnet.webp",
    rating: 2,
    inStock: true,
    inStore: true,
    description: "Complete brush set for intricate nail art designs and professional-quality finishes."
  },
  {
    id: 15,
    name: "Fragrance Mist - Vanilla",
    price: 11.99,
    category: "Fragrance",
    brand: "Mielle",
    imageUrl: "/fragarance.webp",
    rating: 4,
    inStock: false,
    inStore: false,
    description: "Sweet vanilla body mist that leaves you feeling fresh and delicately scented."
  },
  {
    id: 16,
    name: "Jewelries & Accessories Pack",
    price: 24.99,
    category: "Jewelries & Accessories",
    brand: "Shea Moisture",
    imageUrl: "/accessories.webp",
    rating: 3,
    inStock: true,
    inStore: true,
    description: "A curated pack of stylish jewelry and accessories to complement any outfit."
  }
];
